apiVersion: v1
kind: Service
metadata:
  name: osticket
  labels:
    app: osticket
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: osticket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
        group: customer
        tier: frontend
    spec:
      containers:
      - name: osticket
        image: campbellsoftwaresolutions/osticket
        env:
        - name: MYSQL_HOST
          value: osticket-mysql
        - name: MYSQL_PASSWORD
          value: secret
        - name: SMTP_FROM
          value: osticket@tbz-osticket.ch
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: SMTP_PORT
                - name: SMTP_HOST
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: SMTP_PASSWORD               
        ports:
        - containerPort: 80
          name: osticket
